version: 2
updates:
  # Enable version updates for npm with grouping to reduce PR noise
  - package-ecosystem: 'npm'
    # Look for `package.json` and `lock` files in the `root` directory
    directory: '/'
    # Check the npm registry for updates every month
    schedule:
      interval: 'monthly'
    open-pull-requests-limit: 5
    groups:
      # Group all production dependencies together
      production-dependencies:
        patterns:
          - "*"
        exclude-patterns:
          - "@types/*"
          - "*eslint*"
          - "jest"
          - "ts-jest"
          - "typescript"
          - "prettier"
          - "esbuild"
      # Group all development dependencies together  
      development-dependencies:
        patterns:
          - "@types/*"
          - "*eslint*"
          - "jest"
          - "ts-jest"
          - "typescript"
          - "prettier"
          - "esbuild"
    
  # Enable version updates for actions with grouping
  - package-ecosystem: 'github-actions'
    directory: '.github/workflows/'
    # Check for action updates every month
    schedule:
      interval: 'monthly'
    open-pull-requests-limit: 3
    groups:
      # Group all GitHub Actions updates together
      github-actions:
        patterns:
          - "*"
