name: Repo SemVer check
on:
  workflow_dispatch:
  push:  

jobs:
  semver:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        # Check out with fetch-depth: 0 to analyze
        with:
          fetch-depth: 0
      
      - uses: jessehouwing/actions-semver-checker@v1
